# Project information
site_name: 'Zoned Storage'
site_description: 'Linux Zoned Storage Documentation'
# site_url: 'https://westerndigitalcorporation.github.io/zonedstorage.io/'
site_url: 'https://zonedstorage.io/'
docs_dir: docs
site_dir: site

# Repository
# repo_url: 'ssh://git@github.com:westerndigitalcorporation/zonedstorage.io.git'

# Copyright: See footer.html in custom-theme directory

# Configuration (options depends on theme)
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true
  hljs_languages:
    - c
    - bash
    - plaintext
  nav_style: dark
  language: 'en'
  include_sidebar: true

# Customization
plugins:
    - search

# Google Analytics
google_analytics:
  - 'G-D23L5EBB2E'
  - 'auto'

# Extensions
# Require the following python packages:
#    pygments, pymdown-extensions
markdown_extensions:
  - meta
  - admonition
  - fenced_code
  - footnotes
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - toc:
      permalink: false

nav:
 - 'Home': index.md
 - 'Community': community.md
 - 'Documentation':
     - 'Introduction':
         - 'Zoned Storage Overview': introduction/zoned-storage.md
         - 'Shingled Magnetic Recording (SMR) HDDs': introduction/smr.md
         - 'Zoned Namespace (ZNS) SSDs': introduction/zns.md
     - 'Getting Started':
         - 'System Prerequisite': getting-started/prerequisite.md
         - 'Getting Started with an Emulated Zoned Block Device': getting-started/nullblk.md
         - 'Getting Started With SMR Disks': getting-started/smr-disk.md
         - 'Getting Started With Emulated SMR Disks': getting-started/smr-emulation.md
         - 'Getting Started With Emulated NVMe ZNS Devices': getting-started/zns-emulation.md
     - 'Linux Kernel Support':
         - 'Support Overview': linux/overview.md
         - 'Enabling Zoned Block Device Support': linux/config.md
         - 'User Interface': linux/zbd-api.md
         - 'Write Command Ordering': linux/sched.md
         - 'Zoned Block Device Partition Support': linux/part.md
         - 'Device Mapper': linux/dm.md
         - 'File Systems': linux/fs.md
     - 'Tools and Libraries':
         - 'Linux System Utilities': tools/util-linux.md
         - 'Linux Tools for ZNS': tools/zns.md
         - 'SCSI Generic Utilities': tools/sg3utils.md
         - 'libzbc User Library': tools/libzbc.md
         - 'libnvme User Library': tools/libnvme.md
         - 'libzbd User Library': tools/libzbd.md
         - 'tcmu-runner ZBC Disk Emulation': tools/tcmu-runner.md
         - 'QEMU and KVM': tools/qemu.md
     - 'Applications':
         - 'RocksDB': applications/zenfs.md
     - 'System Compliance Tests':
         - 'ZBC/ZAC Compliance Tests': tests/zbc-tests.md
         - 'Kernel Block Layer Tests': tests/blktests.md
     - 'Linux Distributions': distributions/linux.md
     - 'Benchmarking': benchmarking/fio.md
     - 'Frequently Asked Questions': faq/faq.md
 - 'About': about.md

