/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docSidebar: [{type: 'autogenerated', dirName: '.'}],

  community: ['community/support', 'community/devices', 'community/about'],

  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: true,
      items: [
        'introduction/index',
        'introduction/zoned-storage',
        'introduction/smr',
        'introduction/zns',
        'introduction/linux-ecosystem'
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Overview',
          href: '/docs/getting-started',
        },
        'getting-started/linux',
        'getting-started/zbd-emulation',
        'getting-started/smr-disk',
        'getting-started/zns-device'
      ],
    },
    {
      type: 'category',
      label: 'File Systems',
      collapsed: true,
      items: [
        'filesystems/index',
        'filesystems/btrfs',
        'filesystems/f2fs',
        'filesystems/zonefs'
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      collapsed: true,
      items: [
        'applications/index',
        'applications/percona-server',
        'applications/zenfs'
      ],
    },
    {
      type: 'category',
      label: 'Tools and Libraries',
      collapsed: true,
      items: [
        'tools/index',
        'tools/util-linux',
        'tools/zns',
        'tools/sg3utils',
        'tools/libzbc',
        'tools/libzbd',
        'tools/libnvme',
        'tools/tcmu-runner',
        'tools/qemu'
      ],
    },
    {
      type: 'category',
      label: 'Linux Kernel Support',
      collapsed: true,
      items: [
        'linux/index',
        'linux/overview',
        'linux/config',
        'linux/zbd-api',
        'linux/sched',
        'linux/part',
        'linux/dm',
      ],
    },
    {
      type: 'category',
      label: 'System Compliance Tests',
      collapsed: true,
      items: [
        'tests/index',
        'tests/zbc-tests',
        'tests/blktests'
      ],
    },
    {
      type: 'category',
      label: 'Performance Benchmarking',
      collapsed: true,
      items: [
          'benchmarking/index',
          {
              type: 'category',
              label: 'fio',
              collapsed: true,
              items: [
                  'benchmarking/fio/overview',
                  'benchmarking/fio/smr-fio',
                  'benchmarking/fio/zns-fio'
              ]
          },
          'benchmarking/rocksdb',
          'benchmarking/myrocks'
      ]
    },    
    {
      type: 'category',
      label: 'Linux Distributions',
      collapsed: true,
      items: [
           'distributions/overview',
           'distributions/fedora',
           'distributions/opensuse',
           'distributions/ubuntu',
           'distributions/debian',
           'distributions/sles',
           'distributions/centos',
           'distributions/rhel',
           'distributions/arch'
           ]
    },
    {
      type: 'doc',
      label: 'Frequently Asked Questions',
      id: 'faq/faq'
    },
  ],

};

module.exports = sidebars;
